### ISSUE TITLE
Have boilerplate package be pulled in.

### ISSUE THREAD

**Issue by schlessera** [wp-cli/scaffold-package-command#13]
I would recommend changing the way that the package is generated.

As it stands now, the command itself has to know all the details about how a package is structured. It would be cleaner and more maintainable if you had one "boilerplate" package that gets pulled in through `composer create-project` and customized via a `post-create-project-cmd` script.

The command only has to know where to find the boilerplate package, and pull it in, making the code very simple.

The boilerplate package could be easily updated, tests could be run against it, etc... You could even easily provide several different versions of a package if that should be needed.

Was first suggested here: https://github.com/wp-cli/wp-cli/issues/2565

**Comment by danielbachhuber** [comment]
Probably not going to immediately refactor unless this holds some specific advantages, but could be helpful in the future.

**Comment by schlessera** [comment]
The main advantage is that you can have the boilerplate package as a separate repo (maybe even with different branches). Much easier to maintain.

**Comment by ssteinerx** [comment]
@schlessera I have just started my first wp-cli package using this repository and had exactly the same initial reaction.

Having things like `assertEquals` (in features/bootstrap/support.php) in every command is a serious code smell.

What if there turns out to be a bug in one of the included functions?  What if there's an API change in wp-cli that requires a modification in all that duplicate code?

I'm a big fan of scaffolding when the main parts of the scaffolding are factored out into a common code base that is pulled in *once* from a well-maintained repository.

I don't have time to work on this right this moment, but if you want to start a refactor branch, I'll be able to help once my current project is completed.  I can see myself writing a lot of wp-cli commands, and would not want to be pulling in tons of duplicate code for all the reasons above.

**Comment by danielbachhuber** [comment]
> Having things like assertEquals (in features/bootstrap/support.php) in every command is a serious code smell.

Can you be a bit more objective and explain why?

> What if there turns out to be a bug in one of the included functions? What if there's an API change in wp-cli that requires a modification in all that duplicate code?

Then just run `wp scaffold package-tests` again, and overwrite the local files with upstream changes. If your project is tracked in version control, you can easily commit the changes you want, and revert those you don't want.

> I'm a big fan of scaffolding when the main parts of the scaffolding are factored out into a common code base that is pulled in once from a well-maintained repository.

How do you pull in updates and bug fixes then?

**Comment by danielbachhuber** [comment]
FWIW, if you have deep knowledge of Composer, your time would be much better spent (at least initially) on the outstanding issues related to `wp package`: https://github.com/wp-cli/wp-cli/issues?q=is%3Aopen+is%3Aissue+label%3Acommand%3Apackage

**Comment by ssteinerx** [comment]
@danielbachhuber Duplicate code is really never a good thing.  If something is going to be used in every *well formed* plugin e.g. `assertEquals` then it should be factored out into an `asserts` module, and listed as a dependency.  That way only one copy of that code is included no matter how many standard plugins you include in your project.

> Then just run wp scaffold package-tests

That's the point.  This creates extra maintenance -- if the shared module e.g. `asserts` is updated, and you just depend on the latest version, you'll automatically always have the latest code included in your project by virtue of `composer update`.

> How do you pull in updates and bug fixes then?

By updating the core modules e.g. `asserts`.  

I use Composer for everything and for standard modules, I just take the latest version (unless I have a really good reason to pin to a particular release).

With a standard module (which, as far as I can see, would encompass the entire `bin/`, `features/`, and `utils/` directories, a simple `composer update` would get you all the latest, greatest.

That's not to say that I'd necessarily bundle  `bin/`, `features/`, and `utils/` all together; I'd more likely factor out e.g. `asserts` as one module and so on.

As I said, this is the first time I'm using this package, so maybe I've missed something, but it would seem to me that all of this code doesn't belong in every package created to conform to this layout.

**Comment by danielbachhuber** [comment]
Oh. I suppose we might be talking past each other slightly too.

The original intent of this command was to provide _scaffolding_, not be an installable dependency in its own right. For instance, the generated `command.php` is meant to be scaffolded and then modified by the end user — it's not expected to receive any updates over time. Similarly, the scaffolded `.travis.yml` could very well be modified by the end user.

With this being said, the test suite could be abstracted into a dependency that both community commands and WP-CLI could use. When I implemented `wp scaffold package-tests` originally (https://github.com/wp-cli/wp-cli/pull/1309), I couldn't figure out how to have Composer install the Behat steps to where they needed to be. If someone could sort it out, then we could make the Behat steps a separate dependency.

**Comment by ssteinerx** [comment]
Yes, I usually don't use scaffolding type things because of the inability of most of them to be re-run without trashing changes.  It ties you to a specific revision or a very tedious merge process.  That's why I modularize as much as possible.

This repo should contain, in my opinion, only files that may need to be modified which `asserts` for example should not.

I don't have time to work on this right now; I've got to get a plugin written.  I'll revisit before I write my next one, hopefully not under such a tight deadline.

**Comment by danielbachhuber** [comment]
> With this being said, the test suite could be abstracted into a dependency that both community commands and WP-CLI could use.

I still think this is a good idea but, given how few changes there are to WP-CLI's test suite these days, I'm not going to pursue it at this time.
