### ISSUE TITLE
Installation error with new WP-CLI version requirement

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/scaffold-package-command#52]
@aaemnnosttv I'm getting an error with your change in #43

```
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Installation request for runcommand/manifest dev-master -> satisfiable by runcommand/manifest[dev-master].
    - Conclusion: remove wp-cli/wp-cli dev-master
    - runcommand/manifest dev-master requires wp-cli/wp-cli ^0.23.0 -> satisfiable by wp-cli/wp-cli[v0.23.0, v0.23.1].
    - Can only install one of: wp-cli/wp-cli[v0.23.0, dev-master].
    - Can only install one of: wp-cli/wp-cli[v0.23.1, dev-master].
    - Installation request for wp-cli/wp-cli dev-master -> satisfiable by wp-cli/wp-cli[dev-master].
```

Does this make sense to you?

**Comment by aaemnnosttv** [comment]
Ahhh, it turns out the caret operator works differently than I thought for `0.x` versions.

> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.

I think the constraint we're looking for is something like this: `>=0.23`

[Source](https://getcomposer.org/doc/articles/versions.md#caret)

[Here is an awesome tool for testing version constraints I never knew about!](https://semver.mwl.be/#?package=wp-cli%2Fwp-cli&version=%5E0.23.0&minimum-stability=stable)

![image](https://cloud.githubusercontent.com/assets/1621608/18852433/70e9bd5c-8451-11e6-823c-323caa9ff1e3.png)

![image](https://cloud.githubusercontent.com/assets/1621608/18852457/895e03d4-8451-11e6-83c7-77bc88af3a3e.png)

The caret operator is the "recommended operator for maximum interoperability when writing library code" by Composer, but it seems to make the most sense (or assume) the library is released w/ 1.0.0.

Thoughts?

**Comment by danielbachhuber** [comment]
> I think the constraint we're looking for is something like this: `>=0.23`

Cool, works for me 👍

**Comment by aaemnnosttv** [comment]
Cool, I'll try to put together a PR for it soon.
